Repository TechBoutique/TaskBotic-CORE, pull requests merged in 2020-10, with the labels that each got.

#3 BoilerPlate
  initialize.sh
  package-lock.json
  package.json
  src/app.ts
  src/controllers/constants.ts
  src/controllers/taskbotic.controller.ts
  src/database.mysql/database.ts
  src/index.ts
  src/interface/taskbotic.ts
  src/libs/util.ts
  src/libs/verifyToken.ts
  src/routes/taskbotic.routes.ts
  src/services/taskbotic.service.ts
  tsconfig.json
  types.d.ts
Labels: boiler-plate

#12 Integrated prettier with Husky
  .prettierrc.yml
  initialize.sh
  package-lock.json
  package.json
  src/app.ts
  src/controllers/taskbotic.controller.ts
  src/database.mysql/database.ts
  src/interface/taskbotic.ts
  src/libs/util.ts
  src/libs/verifyToken.ts
  src/routes/taskbotic.routes.ts
  src/services/taskbotic.service.ts
Labels: good first issue

#13 Sample API call for calling BRIDGE API's
  package-lock.json
  package.json
  src/controllers/taskbotic.controller.ts
  src/routes/taskbotic.routes.ts
  src/services/participant_master.service.ts
  tsconfig.json
Labels: API's

#14 SQL insertion for Participant data into master_participant_table
  package.json
  src/controllers/taskbotic.controller.ts
  src/routes/taskbotic.routes.ts
  src/services/participant_master.service.ts
Labels: API's, database
